class Product {
  final String id;
  final String name;
  final String description;
  final double price;
  final String imageUrl;
  final String category;
  final double rating;
  final int reviewCount;

  Product({
    required this.id,
    required this.name,
    required this.description,
    required this.price,
    required this.imageUrl,
    required this.category,
    this.rating = 4.5,
    this.reviewCount = 0,
  });

  bool get hasImage => imageUrl.isNotEmpty;

  static List<Product> sampleProducts = [
    Product(
      id: '1',
      name: 'ميني بيتزا',
      description: 'بيتزا صغيرة بحجم مثالي، مقرمشة ولذيذة، مثالية للوجبات الخفيفة.',
      price: 10.0,
      imageUrl: 'assets/images/ميني بيتزا.jpeg',
      category: 'فطائر',
      rating: 4.5,
      reviewCount: 45,
    ),
    Product(
      id: '2',
      name: 'بسبوسة بالقشطة',
      description: 'بسبوسة ناعمة محشوة بالقشطة الطازجة، مغطاة بالشيرة الذهبية.',
      price: 25.0,
      imageUrl: 'assets/images/بسبوسة بالقشطة.jpeg',
      category: 'حلويات',
      rating: 4.8,
      reviewCount: 92,
    ),
    Product(
      id: '3',
      name: 'بسكويت منين',
      description: 'بسكويت منين الهش، بنكهة الزبدة الطازجة، مقرمش ولذيذ.',
      price: 20.0,
      imageUrl: 'assets/images/بسكويت منين.jpeg',
      category: 'بسكويت',
      rating: 4.6,
      reviewCount: 78,
    ),
    Product(
      id: '4',
      name: 'بسكويت نشادر',
      description: 'بسكويت النشادر التقليدي، هش وخفيف، مثالي مع الشاي.',
      price: 18.0,
      imageUrl: 'assets/images/بسكويت نشادر.jpeg',
      category: 'بسكويت',
      rating: 4.4,
      reviewCount: 63,
    ),
    Product(
      id: '5',
      name: 'بسكويت يانسون',
      description: 'بسكويت اليانسون العطري، مقرمش وبنكهة اليانسون المميزة.',
      price: 18.0,
      imageUrl: 'assets/images/بسكويت يانسون.jpeg',
      category: 'بسكويت',
      rating: 4.3,
      reviewCount: 55,
    ),
    Product(
      id: '6',
      name: 'بيتيفور',
      description: 'بيتيفور الزبدة الفاخر، مزين بالمربى والشوكولاتة، يذوب في الفم.',
      price: 30.0,
      imageUrl: 'assets/images/بيتيفور.jpeg',
      category: 'بسكويت',
      rating: 4.7,
      reviewCount: 88,
    ),
    Product(
      id: '7',
      name: 'خلية نحل',
      description: 'خبز خلية النحل الطري، محشو بالجبن أو الزعتر، مخبوز طازجاً.',
      price: 22.0,
      imageUrl: 'assets/images/خلية نحل.jpeg',
      category: 'خبز',
      rating: 4.6,
      reviewCount: 71,
    ),
    Product(
      id: '8',
      name: 'سينامون رولز',
      description: 'لفائف القرفة الناعمة مع طبقة كريمة الجبن، مغطاة بصوص الفانيليا.',
      price: 28.0,
      imageUrl: 'assets/images/سينامون رولز.jpeg',
      category: 'حلويات',
      rating: 4.9,
      reviewCount: 134,
    ),
    Product(
      id: '9',
      name: 'غُريبة',
      description: 'الغريبة التقليدية الهشة، مصنوعة من السميد والزبدة، تتفتت في الفم.',
      price: 20.0,
      imageUrl: 'assets/images/غُريبة.jpeg',
      category: 'بسكويت',
      rating: 4.5,
      reviewCount: 66,
    ),
    Product(
      id: '10',
      name: 'فطاير مشكلة',
      description: 'تشكيلة من الفطائر الطازجة بالجبن والزعتر واللحم، مخبوزة يومياً.',
      price: 35.0,
      imageUrl: 'assets/images/فطاير مشكلة.jpeg',
      category: 'فطائر',
      rating: 4.7,
      reviewCount: 103,
    ),
    Product(
      id: '11',
      name: 'كعك بالعجوة',
      description: 'كعك العجوة التقليدي، محشو بالتمر الطازج، مغطى بالسكر الناعم.',
      price: 25.0,
      imageUrl: 'assets/images/كعك بالعجوة.jpeg',
      category: 'بسكويت',
      rating: 4.6,
      reviewCount: 85,
    ),
    Product(
      id: '12',
      name: 'كعك سادة',
      description: 'كعك سادة هش، بنكهة اليانسون والسمسم، مثالي للإفطار.',
      price: 15.0,
      imageUrl: 'assets/images/كعك سادة.jpeg',
      category: 'بسكويت',
      rating: 4.4,
      reviewCount: 59,
    ),
    Product(
      id: '13',
      name: 'كنافة بالقشطة',
      description: 'كنافة ناعمة بالقشطة الفاخرة، مغطاة بالفستق الحلبي والشيرة.',
      price: 35.0,
      imageUrl: 'assets/images/كنافة بالقشطة.jpeg',
      category: 'حلويات',
      rating: 4.9,
      reviewCount: 156,
    ),
    Product(
      id: '14',
      name: 'كوكيز',
      description: 'كوكيز الشوكولاتة المقرمش من الخارج والطري من الداخل.',
      price: 15.0,
      imageUrl: 'assets/images/كوكيز.jpeg',
      category: 'بسكويت',
      rating: 4.5,
      reviewCount: 112,
    ),
    Product(
      id: '15',
      name: 'كوكيز مع الأسماء',
      description: 'كوكيز مخصص بأسماء، هدية مثالية لمن تحب، طعم رائع.',
      price: 20.0,
      imageUrl: 'assets/images/كوكيز مع الاسماء.jpeg',
      category: 'بسكويت',
      rating: 4.7,
      reviewCount: 95,
    ),
    Product(
      id: '16',
      name: 'كيك شوكلاتة',
      description: 'كيك الشوكولاتة الفاخر، غني بالكاكاو وطبقات الكريمة البلجيكية.',
      price: 120.0,
      imageUrl: 'assets/images/كيك شوكلاتة.jpeg',
      category: 'كيك',
      rating: 4.8,
      reviewCount: 143,
    ),
    Product(
      id: '17',
      name: 'لانكشير',
      description: 'خبز اللانكشير الطري والمخبوز طازجاً، مثالي للسندويشات.',
      price: 12.0,
      imageUrl: 'assets/images/لانكشير.jpeg',
      category: 'خبز',
      rating: 4.3,
      reviewCount: 48,
    ),
  ];
}
